casir_messenger/urls.py
# -*- coding: utf-8 -*-

# Standard library imports
from __future__ import unicode_literals

from django.conf.urls import patterns
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^403/$', TemplateView.as_view(template_name="403.html")),
                       url(r'^404/$', TemplateView.as_view(template_name="404.html")),
                       url(r'^500/$', TemplateView.as_view(template_name="500.html")),
                       url(r'^503/$', TemplateView.as_view(template_name="503.html")),
                       url(r'^membre/', include("members.urls", namespace="members")),
                       url(r'^dashboard/', include("dashboard.urls", namespace="dashboard")),
                       url(r'', include("promotion.urls", namespace="promotion")),
                       )

if settings.DEBUG:
    # Add the Debug Toolbar's URLs to the project's URLconf
    import debug_toolbar
    urlpatterns += patterns('', url(r'^__debug__/', include(debug_toolbar.urls)),)

    # In DEBUG mode, serve media files through Django.
    urlpatterns += staticfiles_urlpatterns()
    # Remove leading and trailing slashes so the regex matches.
    media_url = settings.MEDIA_URL.lstrip('/').rstrip('/')
    urlpatterns += patterns('', url(r'^%s/(?P<path>.*)$' % media_url, 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),)

dashboard/urls.py
# -*- coding: utf-8 -*-

# Standard library imports
from __future__ import unicode_literals
from django.conf.urls import patterns, url


urlpatterns = patterns('',
                       url(r'^index/$', 'dashboard.views.index', name="index"),
                       url(r'^index/(?P<friend_pk>[\d]+)/$', 'dashboard.views.index', name="index"),
                       url(r'^remove/(?P<friend_pk>[\d]+)/$', 'dashboard.views.remove_friend', name="remove"),
                       url(r'^new_message/$', 'dashboard.views.new_message', name="new_message"),
                       url(r'^chargerMessage$', 'dashboard.views.chargerMessage', name="chargerMessage"),
                       )

members/urls.py
# -*- coding: utf-8 -*-

# Standard library imports
from __future__ import unicode_literals
from django.conf.urls import patterns, url


urlpatterns = patterns('',
                       url(r'^se-deconnecter/$', 'django.contrib.auth.views.logout', {'next_page': "/"}, name="logout"))

dashboard/forms.py
# -*- coding: utf-8 -*-

# Standard library imports
from __future__ import unicode_literals

dashboard/views.py
# -*- coding: utf-8 -*-

# Standard library imports
from __future__ import unicode_literals

from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from members.models import Member
from messaging.models import Message
from members.forms import AddFriendForm
from members.forms import PendingRequestForm
from messaging.forms import newMessageForm

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render

import json
from django.http import JsonResponse
@login_required
def index(request, friend_pk = None):
    current_member = request.user.member
    if request.method == "POST":
        if "add_friend_request" in request.POST:
            add_friend_form = AddFriendForm(member=current_member, data=request.POST)
            pending_request_form = PendingRequestForm(member=current_member)
            if add_friend_form.is_valid():
                for member in add_friend_form.cleaned_data["members"]:
                    member.friend_requests.add(current_member)
                add_friend_form = AddFriendForm(member=current_member)

                messages.success(request, "Demandes d'ajout effectuées avec succès")
        else:
            pending_request_form = PendingRequestForm(member=current_member, data=request.POST)
            add_friend_form = AddFriendForm(member=current_member)
            if pending_request_form.is_valid():
                if "refuse_pending_request" in request.POST:
                    for member in pending_request_form.cleaned_data["members"]:
                        current_member.friend_requests.remove(member)
                        messages.success(request, "Demandes en attente refusées avec succès")
                elif "accept_pending_request" in request.POST:
                    for member in pending_request_form.cleaned_data["members"]:
                        current_member.friend_requests.remove(member)
                        current_member.friends.add(member)
                    messages.success(request, "Demandes en attente acceptées avec succès")
            else:
                messages.warning(request, "Demandes en attente : opération annulée")
    elif request.method == "GET":
        add_friend_form = AddFriendForm(member=current_member)
        pending_request_form = PendingRequestForm(member=current_member)

    friends = current_member.friends.all()
    friend_requests = current_member.friend_requests.all()
    
    if friend_pk is not None :
        friend_en_cours = Member.objects.get(pk=friend_pk)
        liste_message = Message.objects.all().filter(recipient=current_member).filter(author=friend_en_cours).order_by("-created_on")
    else :
        friend_en_cours = None
        liste_message = Message.objects.all().filter(recipient = current_member).order_by("-created_on")
    page = request.GET.get('page')
    paginator = Paginator(liste_message, 5) # Show 5 messages per page

    try:
        messagesList = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        messagesList = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        messagesList = paginator.page(paginator.num_pages)

#     if(trie) :
#         liste_message = Message.objects.all().filter(recipient = current_member).filter(author= friend.pk)
        
    context = {'friends': friends,
               'friend_requests': friend_requests,
               'add_friend_form': add_friend_form,
               'liste_message':liste_message,
               'pending_request_form': pending_request_form,
               'messagesList' : messagesList}

    return render(request, "dashboard/index.html", context)


@login_required
def remove_friend(request, friend_pk):
    current_member = request.user.member
    removed_friend = get_object_or_404(Member, pk=friend_pk)
    current_member.friends.remove(removed_friend)
    messages.success(request, "Suppression effectuée avec succès")
    return redirect("dashboard:index")

def new_message(request):
    current_member = request.user.member
    if request.method == "GET":
        new_message_form = newMessageForm(member=current_member, initial={"author": current_member})
    elif request.method == "POST":

        new_message_form = newMessageForm(member=current_member, initial={"author": current_member}, data=request.POST, files=request.FILES)
        if "new_message" in request.POST :
            #print(new_message_form.errors)
            if new_message_form.is_valid():
                new_message = Message( author=new_message_form.cleaned_data["author"],
                                   recipient = new_message_form.cleaned_data["recipient"], 
                                   is_read=False, 
                                   content=new_message_form.cleaned_data["content"],
                                   duration = new_message_form.cleaned_data["duration"], 
                                   picture = new_message_form.cleaned_data["picture"])
                new_message.save()
                messages.success(request, "Message envoyé avec succès")
                
    
    context = {'new_message_form' : new_message_form}
    
    return render(request, "dashboard/message.html", context)

def chargerMessage(request):
    
    idMsg = request.POST.get("id")
    msg = Message.objects.get(id=idMsg)
    msg.is_read = True
    msg.save()
    data = {'msg':msg.content, 'duree':msg.duration, 'pathPhoto' : msg.picture.url if msg.picture else None}
    return JsonResponse(data)

dashboard/templates/dashboard/base.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block extrastyles %}<link href="{% static 'css/dashboard.css' %}" rel="stylesheet">{% endblock %}

{% block content %}

<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
		{% for message in messages %}
			<div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ message }}</div>
		{% endfor %}
	</div>
</div>

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12">
			<div class="jumbotron">
			  <h1>Dashboard</h1>
			  <p>Vous pouvez gérer vos messages et vos amis depuis cet espace !</p>
			</div>
		</div>
	</div>

    {%  block dashboard_inner %}
    {% endblock dashboard_inner %}
</div>
{% endblock content %}

dashboard/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}
{% load staticfiles %}

{% block body_id %}id_dashboard_index{% endblock body_id %}

{%  block dashboard_inner %}
<div class="row">
    <div class="col-sm-3 col-md-2">
        <div class="panel panel-default">
          <div class="panel-heading">Mes amis</div>
                <ul class="list-group">
                    {% for friend in friends %}
                        <li class="list-group-item">
                        	<a href="{% url 'dashboard:index' friend_pk=friend.pk %}" title="Voir les détails de {{ friend.user.username }}">{{ friend.user.username }}</a> 
                        	<a href="{% url 'dashboard:remove' friend_pk=friend.pk %}" title="Supprimer {{ friend.user.username }} de mes amis"><span class="glyphicon glyphicon-remove-circle" aria-hidden="true" style="float: right;"></span></a></li>
                    {% endfor %}
                </ul>

                  <div class="panel-body">
                      <button type="button" class="btn btn-success btn-block" data-toggle="modal" data-target="#id_add_friend_modal">Ajouter un ami</button>
                  </div>

        </div>
    </div>

    <div class="col-sm-9 col-md-10">
        <div class="row">
            <div class="col-sm-3 col-md-2"><a href="{% url 'dashboard:new_message' %}"><button type="button" class="btn btn-success" title="Nouveau message" data-toggle="modal" data-target="#id_new_message_modal">Nouveau message</button></a></div>
            <div class="col-sm-3 col-md-2"><button type="button" class="btn btn-success" title="Demandes en attente" data-toggle="modal" data-target="#id_waiting_friends_modal">Demandes en attente <span class="badge">{{ friend_requests|length }}</span></button></div>
        </div>

        <div class="row" id="id_messages_list_row">
            <div class="col-sm-12">
              <table class="table table-hover">
                  <thead>
                    <tr>
                      <th>Pseudo</th>
                      <th>Date</th>
                      <th>Etat</th>
                    </tr>
                  </thead>

                  <tbody>
	                  	{% for message in messagesList %}
	                    	{% if message.is_read %}
	                    		<tr class="success">
	                    	{% else %}
	                    		<tr class="danger" onclick="setModalMessage(this);">
	                    	{% endif %}
		                    	<td><span class="idMsg" style="display:none;">{{ message.id }}</span><span class="destMsg">{{ message.author.user  }}</span></td>
			                    <td>{{ message.created_on|date:'d-m-Y'}}</td>
			                    <td>
			                    	{% if message.is_read %}
			                    		Lu
			                    	{% else %}
			                    		Non lu
			                    	{% endif %}
			                    </td>
	                    	</tr>
	                    {% endfor %}
	                    
	                    
	                
	                
                    
                  </tbody>
              </table>

                <nav class="pull-right">
                  <ul class="pagination pagination-centered">
			            {% if liste_messages.has_previous %}
			                <li><a href="?page=1"><<</a></li>
			                <li><a href="?page={{ messagesList.previous_page_number }}"><</a></li>
			            {% endif %}
			
			            {% for i in messagesList.paginator.page_range %}
			                <li {% if messagesList.number == i %} class="active" {% endif %}><a href="?page={{i}}">{{i}}</a></li>
			            {% endfor %}
			
			            {% if liste_messages.has_next %}
			                <li><a href="?page={{ messagesList.next_page_number }}">></a></li>
			                <li><a href="?page={{ messagesList.paginator.num_pages }}">>></a></li>
			            {% endif %}
			        </ul>
                </nav>
                
                
            </div>
        </div>
    </div>

<div class="modal fade" id="id_add_friend_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Ajouter un ami</h4>
      </div>
      <form method='POST' action =".">
      {% csrf_token %}
      <div class="modal-body">
        <table class="table table-hover">
          <thead>
            <tr>
              <th colspan="2">Pseudo</th>
            </tr>
          </thead>
          {% for friend in add_friend_form.members.field.choices %}
            <tr>
              <td class="success">{{ friend.1 }}</td>
              <td><input type="checkbox" name="{{ add_friend_form.members.html_name }}" id="id_{{ add_friend_form.members.html_name }}_{{ forloop.counter }}" value="{{ friend.0 }}"></td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-success" name="add_friend_request">Envoyer une demande d'ajout</button>
      </div>
      </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="id_waiting_friends_modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Demandes d'ajout en attente</h4>
            </div>
            <form method='POST' action =".">
            {% csrf_token %}
                <div class="modal-body">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th colspan="2">Pseudo</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for pending_request in pending_request_form.members.field.choices %}
                            <tr>
                                <td class="success">{{ pending_request.1 }}</td>
                                <td><input type="checkbox" name="{{ pending_request_form.members.html_name }}" id="id_{{ pending_request_form.members.html_name }}_{{ forloop.counter }}" value="{{ pending_request.0 }}"></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger" name="refuse_pending_request">Refuser la/les demandes</button>
                    <button type="submit" class="btn btn-success" name="accept_pending_request">Accepter la/les demandes</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="message_modal">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title">.</h4>
	      </div>
	      <div class="modal-body">
	      	<p value="" id="contenuMsg" class="form-control"></p>
	      	<img id="imgMessage"/>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">Fermer</button>
	      </div>
	    </div><!-- /.modal-content -->
	  </div><!-- /.modal-dialog -->
	</form>
</div><!-- /.modal -->
<script type="text/javascript">
	function setModalMessage(uneLigne) {
		$(uneLigne).removeClass('danger').addClass('success')
			.children().last().html('Lu');
		$(uneLigne).attr('onclick', '')
		var id = $(uneLigne).find('.idMsg').text();
		var dest = $(uneLigne).find('.destMsg').text();
		$.post('{% url 'dashboard:chargerMessage' %}', {id:id, csrfmiddlewaretoken:'{{csrf_token}}'}, function(data){
			$('#message_modal').find('.modal-title').text('Message de ' + dest);
			$('#message_modal').find('p').text(data['msg'])
			$('#imgMessage').attr('src', data['pathPhoto'])
			$('#message_modal').modal();
			setTimeout(function() {$('#message_modal').modal('hide');}, parseInt(data['duree'])*1000);
		});
	}
</script>
{%  endblock dashboard_inner %}

dashboard/templates/dashboard/message.html
{% extends 'dashboard/base.html' %}
{% load staticfiles %}

{% block body_id %}id_dashboard_index{% endblock body_id %}

{%  block dashboard_inner %}
<div class="row">
    <div class="col-md-3">
		<button type="button" class="btn btn-primary" title="Mes messages" onclick="window.location.href='../../dashboard/index/';">Mes messages</button>
    </div>
    <div class="col-md-9">
		<h2>Nouveau message</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
		<form method='POST' action ="." enctype="multipart/form-data">
            {% csrf_token %}
          	{% for error in new_message_form.non_field_errors %}
	            <div class="alert alert-danger" role="alert">{{ error }}</div>
	          {% endfor %}
	          {% for field in new_message_form.hidden_fields %}
	         	{{ field}}
	          {% endfor %} 
	          {% for field in new_message_form %}
	            <div class="form-group {%  if field.errors %}has-error{% endif %}">
	                 {%  if field.errors %}
	                    <label class="control-label">{{ field.label }}: {%  for error in field.errors %}{{ error }} {% endfor %}</label>
	                {% endif %}
	                {{ field }}
	            </div>
	          {% endfor %}         
          		<button type="submit" class="btn btn-primary btn-block btn-lg" name="new_message">Envoyer</button>
        </form>
    </div>
</div>


{%  endblock dashboard_inner %}